services:
  - type: web
    name: tudulu-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --include=dev --legacy-peer-deps && npm run build --workspace=apps/api
    startCommand: node apps/api/dist/main
    envVars:
      - key: NODE_ENV
        value: production
